rixaudio/models.py
from . import db

class SubBrand(db.Model):
    __tablename__='subbrands'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    image = db.Column(db.String(60), nullable=False, default = 'defaultcity.jpg')
    products = db.relationship('Product', backref='subbrands', cascade="all, delete-orphan")

    def __repr__(self):
        str = "Id: {}, Name: {}, Image: {}\n" 
        str =str.format( self.id, self.name,self.image)
        return str

orderdetails = db.Table('orderdetails', 
    db.Column('orderid', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('productid',db.Integer,db.ForeignKey('product.id'),nullable=False),
    db.PrimaryKeyConstraint('orderid', 'productid') )

class Product(db.Model):
    __tablename__='product'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    desc = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    weight = db.Column(db.Float, nullable=True)
    model = db.Column(db.String(64), nullable=True)
    subb_id = db.Column(db.Integer, db.ForeignKey('subbrands.id'))
    
    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {}, Price: {}, Weight: {}, Model: {}, SubBrand: {}\n" 
        str =str.format( self.id, self.name,self.desc,self.image, self.price, self.weight, self.model, self.subb_id)
        return str

class Order(db.Model):
    __tablename__='orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    name = db.Column(db.String(64))
    email = db.Column(db.String(128))
    totalcost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    products = db.relationship("Product", secondary=orderdetails, backref="orders")
    
    def __repr__(self):
        str = "id: {}, Status: {}, Name: {}, Email: {}, Date: {}, Product: {}, Total Cost: {}\n" 
        str =str.format( self.id, self.status,self.name, self.email, self.date, self.products, self.totalcost)
        return str

rixaudio/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# form used in cart
class CheckoutForm(FlaskForm):
    name = StringField("", validators=[InputRequired()], render_kw={"placeholder":"Full Name"})
    email = StringField("", validators=[InputRequired(), email()], render_kw={"placeholder":"Email ID"})
    phone = StringField("", validators=[InputRequired()], render_kw={"placeholder":"Phone number"})
    address = StringField("", validators=[InputRequired()], render_kw={"placeholder":"Shipping address"})
    submit = SubmitField("Make Payment")

rixaudio/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()
app=Flask(__name__)

def create_app():
    app.debug=True
    app.secret_key='BetterSecretNeeded123'

    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///rixaudio.sqlite'

    #initialize db with flask app
    db.init_app(app)

    bootstrap = Bootstrap(app)
    
    #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.bp)
   
    return app

@app.errorhandler(404) 
def not_found(e): 
  return render_template("404.html")

@app.errorhandler(500)
def internal_error(e):
  return render_template("500.html")

rixaudio/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import SubBrand, Product, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db


bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    subbrands = SubBrand.query.order_by(SubBrand.name).all()
    p = Product.query.order_by(Product.name).all()
    return render_template('index.html', subbrands = subbrands, products = p)

@bp.route('/products/<subbid>/')
def subbs(subbid):
    subbrands = SubBrand.query.order_by(SubBrand.name).all()
    s = SubBrand.query.filter(SubBrand.id == subbid)
    p = Product.query.filter(Product.subb_id == subbid)
    return render_template('subb.html', products = p, subbrand = s, subbrands = subbrands)

@bp.route('/product/<pid>/')
def product(pid):
    p = Product.query.filter(Product.id == pid)
    subbrands = SubBrand.query.order_by(SubBrand.name).all()
    return render_template('product.html', product = p, subbrands = subbrands)


# Cart | Order Page
@bp.route('/order', methods=['POST','GET'])
def order():
    p_id = request.values.get('p_id')

    # retrieve order if there is one
    if 'orderid'in session.keys():
        order = Order.query.get(session['orderid'])
    else:
        order = None

    # create new order if not exist
    if order is None:
        order = Order(status = False, name='', email='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['orderid'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for op in order.products:
            totalprice = totalprice + op.price
    
    # add item to cart if it doesn't exist
    if p_id is not None and order is not None:
        p = Product.query.get(p_id)
        if p not in order.products:
            try:
                order.products.append(p)
                db.session.commit()
            except:
                return 'Adding Product to Cart resulted in an error.'
            return redirect(url_for('main.order'))
        else:
            flash('This item has already been added to your cart')
            return redirect(url_for('main.order'))
    
    return render_template('order.html', order = order, totalprice = totalprice)


# Delete specific basket items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'orderid' in session:
        order = Order.query.get_or_404(session['orderid'])
        pdel = Product.query.get(id)
        print(pdel)
        try:
            order.products.remove(pdel)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))


# Delete Session
@bp.route('/deleteorder')
def deleteorder():
    if 'orderid' in session:
        del session['orderid']
        flash('All items deleted')
    return redirect(url_for('main.index'))


@bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'orderid' in session:
        order = Order.query.get_or_404(session['orderid'])
       
        if form.validate_on_submit():
            order.status = True
            order.name = form.name.data
            order.email = form.email.data
            totalcost = 0
            for p in order.products:
                totalcost = totalcost + p.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['orderid']
                flash('Thank you for shopping with us! Your shipment will be dispatched soon.')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form = form)

rixaudio/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RIX Audio</title>
    <meta name="description" content="Milton Tours">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/rxa_stylesheet.css')}}">
    
    <title>R I X</title>
</head>

<body>

    <header>
      <!-- navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
          <!-- brand -->
          <a href="{{ url_for('main.index') }}" class="navbar-brand text-light">
              R I X
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Navbar -->
          <div class="collapse navbar-collapse" id="navbarToggler">
            <div class="navbar-nav ml-auto">
                
              <a class="nav-item text-light nav-link x-navitem" href="{{ url_for('main.subbs', subbid="RE") }}">Products</a>
              <a class="nav-item text-light nav-link x-navitem" href="{{url_for('main.order')}}">Cart</a>

            </div>
          </div>

        </div>
      </nav>

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div id="alerttoast" class="x-alert x-shadow bg-success" role="alert" onClick="this.style.display = 'none';">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                </div>
            {% endif %}
        {% endwith %} 

        {% block head %}
        {% endblock %}


    </header>


    <!-- main page content -->
    <div class="container-fluid ">
        <main>
            {% block main %}
            {% endblock %}
        </main>
    </div>

    <!-- footer -->
    <footer class="footer">
      <div class="text-center py-2 bg-light">
        <span class="text-dark">Designed and developed by  <a href="https://rixlayer.dev/" class="badge badge-secondary"> Riju</a></span>
      </div>
    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery Popper.js Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

rixaudio/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}

    <!-- checkout -->
    <section>
      <div class="card bg-light testim x-shadow">
        <div class="card-body">
          <div class="container">
            <div class="row justify-content-around">
            
            <!-- checkout -->
            <div class="col-sm-6">
              <h4 class="card-title">Checkout</h4>
              <p>Billing and delivery details.</p>
              <div style="height:20px"></div>
                    {{wtf.quick_form(form)}}
              </div>
            </div>

        </div>
      </div>
    </section>
    
    <!-- subscribe -->
    <section>
      <div class="card bg-light testim x-shadow">
        <div class="card-body">
          <div class="container">
            <div class="row justify-content-around">
              
              <div class="col-sm-6">
                <h4 class="card-title">Let's Stay in touch</h4>
                <p class="card-title">Get updates on sales specials and more</p>
                <div class="row justify-content-around">
                  <div class="col-sm-8">
                    <div class="input-group">
                      <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Email ID">
                      <div class="input-group-append">
                        <span class="input-group-text">Subscribe</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <div class="col-sm-6">
                <div style="height:10px"></div>
                <h4 class="card-title">Follow Us</h4>
                <div class="container">
                  <div class="row justify-content-center">
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/fb.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/in.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/tw.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/li.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/yt.png')}}"/>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

rixaudio/templates/index.html
{% extends 'base.html' %}

{% block head %}

    <!-- STATIC DATA trending products carousel-->
    <section>
        <div id="productCarouselIndicator" class="carousel slide x-car" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#productCarouselIndicator" data-slide-to="0" class="active"></li>
            <li data-target="#productCarouselIndicator" data-slide-to="1"></li>
            <li data-target="#productCarouselIndicator" data-slide-to="2"></li>
        </ol>
        
        <div class="carousel-inner" role="listbox">

            <!-- STATIC DATA carousel content -->
            <div class="carousel-item active">
            <img class="d-block w-100" href="#" src="{{url_for('static', filename='img/products/REcover.png')}}" alt="First slide">
            <div class="carousel-caption trending-carousel-caption d-none d-md-block">
                <h1>RIX RENO 557</h1>
                <p>The all new RENO powered with rapid web technology.</p>
                <button type="button" class="btn btn-outline-light" onclick="location.href='subb.html'">Check it out</button>
            </div>
            </div>
            
            <div class="carousel-item">
            <img class="d-block w-100" href="#" src="{{url_for('static', filename='img/products/RHcover.png')}}" alt="Second slide">
            <div class="carousel-caption trending-carousel-caption d-none d-md-block">
                <h1>RIX RHEA T7 Pro</h1>
                <p>The RHEA T7 remastered with Extra Bass</p>
                <button type="button" class="btn btn-outline-light" onclick="location.href='subb.html'">Check it out</button>
            </div>
            </div>

            <div class="carousel-item">
            <img class="d-block w-100" href="#" src="{{url_for('static', filename='img/products/RScover.png')}}" alt="Third slide">
            <div class="carousel-caption trending-carousel-caption d-none d-md-block">
                <h1>RIX RESP A1</h1>
                <p>Your favourite bluetooth speaker now with Google Home Integration</p>
                <button type="button" class="btn btn-outline-light" onclick="location.href='subb.html'">Check it out</button>
            </div>
            </div>
        </div>
        
        <!-- carousel controls -->
        <a class="carousel-control-prev" href="#productCarouselIndicator" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#productCarouselIndicator" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        </div>
    </section>
    <div style="height:20px"></div>

{% endblock %}

{% block main %}

    <!-- product categories -->
    <section>
      <div class="card-group">

        {% for subb in subbrands%}
            <div class="card c-cat">
                <img class="card-img" src="{{url_for('static', filename='img/products/'+subb.image)}}" alt="{{subb.name}} Sample">
                <div class="card-img-overlay">
                    <p class="card-text p-c-txt" data-desc=" Series" onclick="location.href='{{ url_for('main.subbs', subbid=subb.id) }}'">{{subb.name}}</p>
                </div>
            </div>
        {% endfor %}

      </div>
    </section>

    <!-- search -->
    <section>
        <div class="card bg-light p-search x-shadow">
            <div class="card-body">
                <h4 class="card-title">Browse our Products</h4>
                
                <div style="height:20px"></div>

                <div id="pSearchResults" class="card-deck justify-content-center" style="display:flex">
                    
                    {% for p in products%}
                        <div class="card p-c-search x-card x-shadow col-sm-2">
                            <h6>{{p.name}}</h6>
                            <img class="card-img-top" src="{{url_for('static', filename='img/products/'+p.image)}}" alt="{{p.name}} Image">
                            <p class="text-primary p-s-r-txt">{{p.price}}</p>
                            <button type="button" class="btn btn-light w-100 btn-sm p-s-r-btn" style="border-radius:20px"
                              onclick="location.href='{{ url_for('main.product', pid=p.id) }}'">View Details</button>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </section>

    <!-- why choose RIX -->
    <section>
      <div class="card bg-light testim x-shadow">
        <div class="card-body">
          <h4 class="card-title">Why choose RIX?</h4>
          <p class="lead">
            We have exceptional standards, attention to detail and experienced tradesmen. </br>
            We listen carefuly and deliver with pride and passion exactly what our customers need. </br>
            Our products are a fuse of the highest grade materials and latest technology. </br>
            All our products have a 5 year warranty, that's how confident we are about our quality. </br>
            We are a trusted partner of the QUT Council of Equipment. 
          </p>
          <a href="#!" class="card-link mis-state-link" data-desc=" about our Mission Statement">Read more</a>
        </div>
      </div>
    </section>

    <!-- contact -->
    <section>
      <div class="card bg-light testim x-shadow">
        <div class="card-body">
          <div class="container">
            <div class="row justify-content-around">
            
            <div class="col-sm-8">
              <h4 class="card-title">Talk to Us</h4>
              <div style="height:20px"></div>
                <form>
                  <div class="form-group">
                    <textarea class="span6 form-control" rows="3" id="formGroupExampleInput" placeholder="What's up?" required></textarea>
                  </div>
                  <div class="input-group mb-2 mr-sm-2">
                    <div class="input-group-prepend">
                      <div class="input-group-text">@</div>
                    </div>
                    <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Email ID">
                    <div class="input-group-append">
                      <span class="input-group-text">Send</span>
                    </div>
                  </div>
                </form>
              </div>
            </div>
        </div>
      </div>
    </section>

    <!-- partners -->
    <section>
      <div class="card bg-light partnrs x-shadow">
        <div class="card-body">
          <h4 class="card-title">Our Partners</h4>
          
          <div class="container">
            <div class="row justify-content-center">
                <img class="partnrs-logo col-sm-2" src="{{url_for('static', filename='img/logo/qut.png')}}"/>
                <img class="partnrs-logo col-sm-2" src="{{url_for('static', filename='img/logo/sef.png')}}"/>
                <img class="partnrs-logo col-sm-2" src="{{url_for('static', filename='img/logo/qg.png')}}"/>
                <img class="partnrs-logo col-sm-2" src="{{url_for('static', filename='img/logo/fc.png')}}"/>
                <img class="partnrs-logo col-sm-2" src="{{url_for('static', filename='img/logo/qes.png')}}"/>
                <img class="partnrs-logo col-sm-2" src="{{url_for('static', filename='img/logo/hiq.png')}}"/>
            </div>
            <hr>
          </div>
          
          <a href="#!" class="card-link mis-state-link" data-desc=" as a featured Partner">Join us</a>
        </div>
      </div>
    </section>

    <!-- subscribe -->
    <section>
      <div class="card bg-light testim x-shadow">
        <div class="card-body">
          <div class="container">
            <div class="row justify-content-around">
              
              <div class="col-sm-6">
                <h4 class="card-title">Let's Stay in touch</h4>
                <p class="card-title">Get updates on sales specials and more</p>
                <div class="row justify-content-around">
                  <div class="col-sm-8">
                    <div class="input-group">
                      <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Email ID">
                      <div class="input-group-append">
                        <span class="input-group-text">Subscribe</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <div class="col-sm-6">
                <div style="height:10px"></div>
                <h4 class="card-title">Follow Us</h4>
                <div class="container">
                  <div class="row justify-content-center">
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/fb.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/in.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/tw.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/li.png')}}"/>
                    <img class="social-logo col-sm-2" src="{{url_for('static', filename='img/social/yt.png')}}"/>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

rixaudio/templates/order.html
{% extends 'base.html' %}

{% block main %}

   <!-- cart -->
    <section>
        <div class="card bg-light p-search x-shadow">
            <div class="card-body">
                <h4 class="card-title">Your Cart</h4>
                
                <div style="height:20px"></div>

                <div id="pSearchResults" class="card-deck justify-content-center" style="display:flex">
                    
                    {% for p in order.products%}
                        <div class="card p-c-search x-card x-shadow col-sm-2" onclick="location.href='{{ url_for('main.product', pid=p.id) }}'">
                            <h6>{{p.name}}</h6>
                            <img class="card-img-top" src="{{url_for('static', filename='img/products/'+p.image)}}" alt="{{p.name}} Image">
                            <p class="text-primary p-s-r-txt">A${{p.price}}</p>

                            <!-- delete item -->
                            <form method="POST" action="{{url_for('main.deleteorderitem')}}" class="w-100">
                                <input type="hidden" id="id" name="id" value="{{p.id}}">
                                <input type="submit" value="Remove" class="btn btn-outline-danger w-100 btn-sm p-s-r-btn" style="border-radius:20px">
                            </form>
                        </div>
                    {% endfor %}
                </div>
                
            </div>
        </div>
    </section>

    <!-- checkout -->
    <section>
        <div class="card bg-light x-card x-shadow">
            <div class="card-body col-sm-12">
                <div class="row justify-content-center">

                    <!-- view cart -->
                    <div class="col-sm-2" style="text-align:center">
                        <button type="button" class="btn btn-outline-secondary" onclick="location.href='{{ url_for('main.subbs', subbid='RE') }}'">Continue Shopping</button>
                    </div>

                    <!-- empty cart -->
                    <div class="col-sm-2" style="text-align:center">
                        <a href="{{ url_for('main.deleteorder') }}" class="btn btn-outline-danger">Empty Cart</a>
                    </div>

                    <!-- total price -->
                    <div class="col-sm-3">
                        <h2 style="text-align:center"> A${{ "%.2f"|format(totalprice) }} </h2>
                    </div>

                    <!-- checkout -->
                    <div class="col-sm-2" style="text-align:center">
                        <a href="{{ url_for('main.checkout') }}" class="btn btn-secondary">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

rixaudio/templates/subb.html
{% extends 'base.html' %}

{% block main %}

<section>
    <section>
        <div id="productCarouselIndicator" class="carousel slide" data-ride="carousel">       
            <div class="carousel-inner p-carousel" role="listbox">

                <!-- carousel content -->
                {% for s in subbrand%}
                    <div class="carousel-item active">
                        <img class="d-block w-100" href="#" src="{{url_for('static', filename='img/products/'+s.id+'cover.png')}}" alt="First slide">
                    </div>
                    <div class="carousel-caption p-carousel-caption d-md-block">
                        <h1 class="p-title">{{s.name}}</h1>
                    </div>
                {% endfor %}
            </div>
        </div>   
    </section>

    <section>
        <div class="card bg-light p-search x-shadow">
            <div class="card-body">
                
                <!-- subbrand radio group-->
                <div class="container col-mr-8">
                    <div class="row justify-content-center">

                        <div class="btn-group btn-group-toggle p-s-select text-center" data-toggle="buttons">
                            {% for s in subbrand%}
                                {% for subb in subbrands%}
                                    {% if s != subb%}
                                    <label name="seriesRadio" class="btn btn-outline-dark" onclick="location.href='{{ url_for('main.subbs', subbid=subb.id) }}'">
                                        <input type="radio" name="options" id="option_{{subb.id}}" autocomplete="off">{{subb.name}}</label>
                                    {% endif %}
                                    {% if s == subb%}
                                    <label name="seriesRadio" class="btn btn-outline-dark active">
                                        <input type="radio" name="options" id="option_{{subb.id}}" autocomplete="off">{{subb.name}}</label>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!-- search results | product list -->
                <div id="pSearchResults" class="card-deck justify-content-center" style="display:flex">
                    {% for p in products%}
                        <div class="card p-c-search x-card x-shadow col-sm-2">
                            <h6>{{p.name}}</h6>
                            <img class="card-img-top" src="{{url_for('static', filename='img/products/'+p.image)}}" alt="{{p.name}} Image">
                            <p class="text-primary p-s-r-txt">{{p.price}}</p>
                            <button type="button" class="btn btn-light w-100 btn-sm p-s-r-btn" style="border-radius:20px" onclick="location.href='{{ url_for('main.product', pid=p.id) }}'">View Details</button>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>


    <!-- product categories -->
    <section>
      <div class="card-group">

        {% for subb in subbrands%}
            <div class="card c-cat">
                <img class="card-img" src="{{url_for('static', filename='img/products/'+subb.image)}}" alt="{{subb.name}} Sample">
                <div class="card-img-overlay">
                    <p class="card-text p-c-txt" data-desc=" Series" onclick="location.href='{{ url_for('main.subbs', subbid=subb.id) }}'">{{subb.name}}</p>
                </div>
            </div>
        {% endfor %}

      </div>
    </section>

</section>
{% endblock %}